Fixing Julia versions
GEO-BON/bon-in-a-box-pipelines pull request #114
Opened 2023-10-11 14:27 UTC by gottacatchenall

This currently this instantiates the project at the root, but each script is run in the  `/scripts/<SCRIPT_NAME` and uses that as the project by default. Easiest way around this would be to have `Pkg.activate("/")`, though there may be some long-term benefit in having individual `Project.toml`'s for each script that are all installed when the Julia docker image is built

2023-10-12 21:09 UTC, tpoisot commented
> This currently this instantiates the project at the root, but each script is run in the /scripts/<SCRIPT_NAME and uses that dir as the project by default. 

We can also install the required packaged in the container's default (`@1.whatever`) environment and only add the required packages to each script's `Project.toml`. When starting julia with `--project`, the default environment remains accessible (I think?)

2023-10-12 21:13 UTC, tpoisot commented on runners/julia-dockerfile
> +# RUN  julia -e 'pwd(); using Pkg; Pkg.add.(["SpeciesDistributionToolkit", "Dates", "Clustering", "JSON", "CSV", "DataFrames", "StatsBase", "EvoTrees", "MultivariateStats" ]); Pkg.instantiate();'
this should probably use https://pkgdocs.julialang.org/v1/api/#Pkg.PackageSpec to make sure we set the version of each package

2023-10-20 17:07 UTC, jmlord requested changes

2023-10-20 18:11 UTC, gottacatchenall commented
I have added the scripts and made a version of instantiate that installs and precompiles and environment for each Julia script (right now only helloWorld.jl is on main)

2024-09-19 20:37 UTC, gottacatchenall commented
i'll do this somewhere else :(

2024-09-19 20:37 UTC, closed without merging